import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// Create Supabase client
const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!
);

export async function GET(request: NextRequest) {
  try {
    const { data, error } = await supabase
      .from('purchase_orders')
      .select(`
        *,
        vendor:vendors(*),
        intend:intends(*),
        po_items(
          *,
          ingredient:ingredients(*)
        )
      `)
      .order('created_at', { ascending: false });

    if (error) throw error;

    return NextResponse.json({ data });
  } catch (error: any) {
    console.error('Error fetching purchase orders:', error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();

    // Create PO (po_number will be auto-generated by database function)
    const { data: po, error: poError } = await supabase
      .from('purchase_orders')
      .insert({
        intend_id: body.intend_id,
        vendor_id: body.vendor_id,
        status: body.status || 'pending',
        total_amount: body.total_amount || 0,
        total_items_count: body.items?.length || 0,
        payment_status: 'unpaid',
      })
      .select()
      .single();

    if (poError) throw poError;

    // Insert PO items
    if (body.items && body.items.length > 0) {
      const itemsToInsert = body.items.map((item: any) => ({
        po_id: po.id,
        ingredient_id: item.ingredient_id,
        intend_item_id: item.intend_item_id,
        quantity_ordered: item.quantity_ordered,
        unit_price: item.unit_price,
      }));

      const { error: itemsError } = await supabase
        .from('po_items')
        .insert(itemsToInsert);

      if (itemsError) throw itemsError;
    }

    return NextResponse.json({ success: true, po });
  } catch (error: any) {
    console.error('Error creating purchase order:', error);
    return NextResponse.json(
      { error: error.message },
      { status: 500 }
    );
  }
}
